### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by pandaB1t** [Mirzohid22/pointhub#1]
### I opened the site and saw the error

```bash 
Applicationerror: a client-side exception has occurred 
```

**Comment by Mirzohid22** [comment]
### Appreciation for Your Contribution - Issue Resolved!
Hey 👋🙂 @pandaB1t 

the problem was: mishandling an unexpected response from our API, I fixed it  [here](https://github.com/Mirzohid22/pointhub/commit/9e1470a8b408a0c5317a3794d351394d06886000)

Big thanks for spotting the issue! 
I'm genuinely grateful for your contribution. It's awesome having users like you who care about making other's code better. If you come across anything else or have more ideas, feel free to drop them here.

Thanks again, and looking forward to more collaborations!

Best regards
Mirzohid
